language: go

install:
  - go get -u github.com/golang/lint/golint
  # This is default if `install` not overridden:
  - go get -t -v ./...

before_script:
  - ./check_gofmt.sh

script: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
