language: go

install:
  - go get -u golang.org/x/lint/golint
  # This is default if `install` not overridden:
  - go get -t -v ./...

before_script:
  - ./check_gofmt.sh

script: ./.travis-ci-coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
